### ISSUE TITLE
Using an LC4032 chip with 48 pins

### ISSUE THREAD

**Issue by equalizor** [Kekule-OXC/aladdin-xt-cpld#1]
Is it possible to use the LC4032V75TN-10I 48 pin with this code? I mean I know a handful of pins are different, but if I modified the pin definitions would that work? I've created my a version of this ModChop (for personal use) and I've just followed the pin map names, not pin number to match the various signals from the CPLD to the Flash and LPC header. I'd like to know if this will work because the 48 pin variant is available on Ali whereas I can't find the 44 pin variant anywhere.

**Comment by Kekule-OXC** [comment]
sure, if you remade the board for the 48 pin version

**Comment by equalizor** [comment]
I already have, so thats a winner :-) Is there anything else you think I might need to do to that code for the difference in the pin designations or is that it? I looked through the code files and it all seems pretty straight forward. None of the code seems to reference the pins by physical number so as long as the maps are correct I should be good to go right?

I do have one more question. 

The pins file says that Flash Pin 31/LCLK goes to LPC Clock, but the CPLD pin map says it goes to 39/CLK0 of the CPLD. Does this mean it actually has to go to both?

**Comment by Kekule-OXC** [comment]
correct thats controlled by the mapping.  This isnt an issue.  If you want to ask questions i suggest you join the xbox-scene discord instead.

**Comment by equalizor** [comment]
Thank you very much for your help :-)
